import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import "./globals.css";
// import "";
import logoSeskoal from "../../public/seskoal.png";

// const inter = Inter({ subsets: ["latin"] });

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Monitoring Server Seskoal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // function handleButtonClick() {
  //   console.log('Button clicked');
  // }

  return (
    <html lang="en">
      <body className={`${inter.variable} relative font-inter antialiased`}>
        <div className="navbar bg-neutral text-neutral-content">
          <div className="flex-1">
            <Image
              src={logoSeskoal.src}
              alt="Picture of the author"
              width="100"
              height="100"
              className="bg-mint text-mint fill-current"
            ></Image>
              
          </div>
          
          <div className="flex-2">
            monitoring
          </div>
          <div className="flex-3">
            monitoring
          </div>
        </div>
     
    
        {children}
      </body>
    </html>
  );
}
